language: java
jdk:
- oraclejdk8
before_install:
- chmod +x mvnw
install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
script:
- mvn test
after_sucess:
 - bash <(curl -s https://codecov.io/bash)